"""Initial commit

Revision ID: 789a136cea84
Revises: 
Create Date: 2026-02-02 19:08:50.558228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '789a136cea84'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('name', sa.String(), nullable=False, comment='Название чата'),
    sa.Column('avatar_url', sa.String(), nullable=False, comment='Ссылка на аватар'),
    sa.Column('chat_type', sa.Enum('PERSONAL', 'GROUP_CHAT', name='chattype'), nullable=False, comment='Тип чата'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата обновления'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('first_name', sa.String(), nullable=False, comment='Имя'),
    sa.Column('second_name', sa.String(), nullable=False, comment='Фамилия'),
    sa.Column('patronymic', sa.String(), nullable=True, comment='Отчество'),
    sa.Column('date_of_birth', sa.Date(), nullable=False, comment='Дата рождения'),
    sa.Column('avatar_url', sa.String(), nullable=False, comment='Ссылка на аватар'),
    sa.Column('phone_number', sa.String(), nullable=False, comment='Номер телефона'),
    sa.Column('email', sa.String(), nullable=False, comment='Почта'),
    sa.Column('hashed_password', sa.String(), nullable=False, comment='Hash пароля'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата обновления'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True, comment='Статус пользователя'),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True, comment='Дата последнего посещения'),
    sa.Column('is_online', sa.Boolean(), server_default='false', nullable=False, comment='Статус онлайн'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('chat_id', sa.Integer(), nullable=False, comment='ID чата'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID пользователя'),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата вступления в чат'),
    sa.Column('role', sa.String(), nullable=False, comment='Роль в чате (owner/admin/member)'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
    sa.Column('chat_id', sa.Integer(), nullable=False, comment='ID чата'),
    sa.Column('sender_id', sa.Integer(), nullable=False, comment='ID отправителя'),
    sa.Column('content', sa.String(), nullable=False, comment='Текст сообщения'),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата отправки'),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False, comment='Прочитано ли сообщение'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('chat_members')
    op.drop_table('users')
    op.drop_table('profiles')
    op.drop_table('chats')
    # ### end Alembic commands ###
