"""Initial commit

Revision ID: a7017495af4f
Revises: 
Create Date: 2026-05-03 23:36:22.400370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7017495af4f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID чата'),
    sa.Column('name', sa.String(), nullable=False, comment='Название чата'),
    sa.Column('description', sa.String(), nullable=True, comment='Описание чата (для групповых чатов)'),
    sa.Column('avatar_url', sa.String(), nullable=False, comment='Ссылка на аватар'),
    sa.Column('chat_type', sa.Enum('PERSONAL', 'GROUP_CHAT', name='chattype'), nullable=False, comment='Тип чата'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Активен ли чат'),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True, comment='Дата и время последнего сообщения'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата обновления'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный идентификатор профиля'),
    sa.Column('first_name', sa.String(), nullable=False, comment='Имя пользователя'),
    sa.Column('last_name', sa.String(), nullable=True, comment='Фамилия пользователя (опционально)'),
    sa.Column('patronymic', sa.String(), nullable=True, comment='Отчество пользователя (опционально)'),
    sa.Column('date_of_birth', sa.Date(), nullable=False, comment='Дата рождения пользователя'),
    sa.Column('avatar_url', sa.String(), nullable=False, comment='Ссылка на аватар пользователя'),
    sa.Column('phone_number', sa.String(), nullable=True, comment='Номер телефона пользователя (опционально)'),
    sa.Column('email', sa.String(), nullable=True, comment='Почтовый адрес пользователя (опционально)'),
    sa.Column('bio', sa.String(), nullable=True, comment='Краткое описание пользователя'),
    sa.Column('location', sa.String(), nullable=True, comment='Местоположение пользователя'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата создания профиля'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата последнего обновления профиля'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный идентификатор пользователя'),
    sa.Column('profile_id', sa.Integer(), nullable=False, comment='Ссылка на профиль пользователя'),
    sa.Column('username', sa.String(), nullable=True, comment='Уникальное имя пользователя для входа'),
    sa.Column('email', sa.String(), nullable=True, comment='Почтовый адрес пользователя'),
    sa.Column('phone_number', sa.String(), nullable=True, comment='Номер телефона пользователя'),
    sa.Column('hashed_password', sa.String(), nullable=False, comment='Хэш пароля пользователя (не хранится в открытом виде)'),
    sa.Column('status', sa.String(), nullable=True, comment='Статус пользователя (online, offline, busy, away)'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Активен ли аккаунт пользователя'),
    sa.Column('is_email_verified', sa.Boolean(), server_default='false', nullable=False, comment='Подтвержден ли email пользователя'),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True, comment='Дата и время последнего посещения'),
    sa.Column('is_online', sa.Boolean(), server_default='false', nullable=False, comment='Текущий статус онлайн'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата регистрации пользователя'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата последнего обновления данных'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('profile_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('chat_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный идентификатор участника чата'),
    sa.Column('chat_id', sa.Integer(), nullable=False, comment='ID чата'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID пользователя'),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', name='role'), nullable=False, comment='Роль в чате (owner/admin/member)'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Активен ли пользователь в чате'),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата вступления в чат'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время добавления'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время обновления'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friendships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный идентификатор связи'),
    sa.Column('user1_id', sa.Integer(), nullable=False, comment='ID первого пользователя'),
    sa.Column('user2_id', sa.Integer(), nullable=False, comment='ID второго пользователя'),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'BLOCKED', name='friendshipstatus'), nullable=False, comment='Статус дружеской связи'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания связи'),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True, comment='Дата и время подтверждения дружбы'),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID сообщения'),
    sa.Column('chat_id', sa.Integer(), nullable=False, comment='ID чата'),
    sa.Column('sender_id', sa.Integer(), nullable=False, comment='ID отправителя'),
    sa.Column('content', sa.String(), nullable=False, comment='Текст сообщения'),
    sa.Column('is_edited', sa.Boolean(), server_default='false', nullable=False, comment='Редактировалось ли сообщение'),
    sa.Column('reaction', sa.String(), nullable=True, comment='Реакция на сообщение (эмодзи)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Дата удаления сообщения (для soft delete)'),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата отправки'),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False, comment='Прочитано ли сообщение'),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный идентификатор уведомления'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID пользователя, которому отправлено уведомление'),
    sa.Column('notification_type', sa.Enum('NEW_MESSAGE', 'NEW_FRIEND_REQUEST', 'FRIEND_REQUEST_ACCEPTED', 'MESSAGE_READ', 'SYSTEM', 'ADMIN_MESSAGE', name='notificationtype'), nullable=False, comment='Тип уведомления'),
    sa.Column('title', sa.String(), nullable=False, comment='Заголовок уведомления'),
    sa.Column('message', sa.String(), nullable=False, comment='Текст уведомления'),
    sa.Column('related_id', sa.Integer(), nullable=True, comment='ID связанного объекта (сообщение, чат, пользователь)'),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False, comment='Прочитано ли уведомление'),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True, comment='Дата и время прочтения уведомления'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания уведомления'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_blocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный идентификатор блокировки'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID пользователя, который выполнил блокировку'),
    sa.Column('blocked_user_id', sa.Integer(), nullable=False, comment='ID заблокированного пользователя'),
    sa.Column('blocked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время блокировки'),
    sa.Column('reason', sa.String(), nullable=True, comment='Причина блокировки (опционально)'),
    sa.ForeignKeyConstraint(['blocked_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный идентификатор сессии'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID пользователя'),
    sa.Column('session_token', sa.String(), nullable=False, comment='Уникальный токен сессии (UUID)'),
    sa.Column('device_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Информация об устройстве (UA, OS, браузер)'),
    sa.Column('ip_address', sa.String(), nullable=True, comment='IP-адрес пользователя при входе'),
    sa.Column('user_agent', sa.String(), nullable=True, comment='User-Agent строки браузера'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Дата и время истечения сессии'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Активна ли сессия'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания сессии'),
    sa.Column('last_activity', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время последней активности'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный идентификатор настроек'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID пользователя'),
    sa.Column('show_last_seen', sa.Boolean(), server_default='true', nullable=False, comment='Показывать ли последнее посещение другим пользователям'),
    sa.Column('show_phone_number', sa.Boolean(), server_default='false', nullable=False, comment='Показывать ли номер телефона другим пользователям'),
    sa.Column('show_email', sa.Boolean(), server_default='false', nullable=False, comment='Показывать ли email другим пользователям'),
    sa.Column('notify_new_message', sa.Boolean(), server_default='true', nullable=False, comment='Уведомлять о новых сообщениях'),
    sa.Column('notify_new_friend_request', sa.Boolean(), server_default='true', nullable=False, comment='Уведомлять о новых запросах в друзья'),
    sa.Column('notify_message_read', sa.Boolean(), server_default='false', nullable=False, comment='Уведомлять о прочтении своих сообщений'),
    sa.Column('notify_system', sa.Boolean(), server_default='true', nullable=False, comment='Уведомлять о системных событиях'),
    sa.Column('default_chat_theme', sa.String(), nullable=True, comment='Тема чата по умолчанию'),
    sa.Column('message_auto_delete', sa.Integer(), nullable=True, comment='Автоудаление сообщений (в секундах, 0 = выключено)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания настроек'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время обновления настроек'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('attachments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный идентификатор вложения'),
    sa.Column('message_id', sa.Integer(), nullable=False, comment='ID сообщения, к которому прикреплен файл'),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False, comment='ID пользователя, который загрузил файл'),
    sa.Column('file_type', sa.Enum('IMAGE', 'VIDEO', 'AUDIO', 'DOCUMENT', 'FILE', name='attachmenttype'), nullable=False, comment='Тип файла'),
    sa.Column('file_name', sa.String(), nullable=False, comment='Имя файла'),
    sa.Column('file_url', sa.String(), nullable=False, comment='Ссылка для скачивания файла'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='Размер файла в байтах'),
    sa.Column('mime_type', sa.String(), nullable=True, comment='MIME-тип файла'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время загрузки'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message_read_receipts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный идентификатор подтверждения'),
    sa.Column('message_id', sa.Integer(), nullable=False, comment='ID сообщения'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID пользователя, который прочитал сообщение'),
    sa.Column('read_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время прочтения'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Уникальный идентификатор жалобы'),
    sa.Column('author_id', sa.Integer(), nullable=False, comment='ID пользователя, который подал жалобу'),
    sa.Column('report_type', sa.Enum('SPAM', 'HARMFUL', 'HARASSMENT', 'INSULT', 'COPYRIGHT', 'OTHER', name='reporttype'), nullable=False, comment='Тип жалобы'),
    sa.Column('reported_user_id', sa.Integer(), nullable=True, comment='ID пользователя, на которого подана жалоба'),
    sa.Column('reported_message_id', sa.Integer(), nullable=True, comment='ID сообщения, на которое подана жалоба'),
    sa.Column('description', sa.String(), nullable=True, comment='Описание нарушения'),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'RESOLVED', 'REJECTED', name='reportstatus'), nullable=False, comment='Текущий статус жалобы'),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True, comment='Дата и время завершения рассмотрения'),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True, comment='ID администратора, который рассмотрел жалобу'),
    sa.Column('admin_comment', sa.String(), nullable=True, comment='Комментарий администратора'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время подачи жалобы'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_table('message_read_receipts')
    op.drop_table('attachments')
    op.drop_table('user_settings')
    op.drop_table('user_sessions')
    op.drop_table('user_blocks')
    op.drop_table('notifications')
    op.drop_table('messages')
    op.drop_table('friendships')
    op.drop_table('chat_members')
    op.drop_table('users')
    op.drop_table('profiles')
    op.drop_table('chats')
    # ### end Alembic commands ###
